openapi: 3.0.0
info:
  title: English Submission Correction API
  version: 1.0.0
  description: >
    英文を提出し、AIの添削を受けた結果に対してコメントできるシステムのAPIです。
    ユーザーは管理者登録後にログインし、自身の英文を投稿・添削し、他のユーザーはそれにコメントします。

paths:
  /auth/register:
    post:
      summary: Register a new user (admin only)
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required: [username, password]
      responses:
        '201':
          description: User registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User registered successfully
        '400':
          description: Bad request (missing or invalid parameters)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Username and password are required"
        '409':
          description: Conflict (username already exists)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Username already exists"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "An unexpected error occurred"

  /auth/login:
    post:
      summary: Login with username and password
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required: [username, password]
      responses:
        '200':
          description: Logged in successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Login successful
        '400':
          description: Bad request (missing or malformed parameters)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Missing username or password"
        '401':
          description: Unauthorized (invalid credentials)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid username or password"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "An unexpected error occurred"

  /auth/logout:
    post:
      summary: Logout the current session
      tags: [Auth]
      responses:
        '204':
          description: Session terminated successfully

  /auth/delete:
    delete:
      summary: Delete a user account (admin only)
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
              required: [username]
      responses:
        '200':
          description: Account deleted successfully
        '400':
          description: Missing or invalid username
        '401':
          description: Unauthorized
        '404':
          description: User not found
        '500':
          description: Internal server error

  /submissions/select:
    get:
      summary: Get paginated AI-corrected submissions
      tags: [Submission]
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          required: false
          description: Page number
        - in: query
          name: limit
          schema:
            type: integer
          required: false
          description: Items per page
        - in: query
          name: sortBy
          schema:
            type: string
          required: false
          description: Field to sort by (e.g., date, id)
      responses:
        '200':
          description: A list of corrected submissions
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    text:
                      type: string
                    res:
                      type: string
                    corrections:
                      type: array
                      items:
                        type: object
                        properties:
                          original:
                            type: string
                          corrected:
                            type: string
                          reason:
                            type: string
                    comments:
                      type: array
                      items:
                        type: object
                        properties:
                          user:
                            type: string
                          text:
                            type: string
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

  /submissions/by-user:
    get:
      summary: Get submissions by specific user
      tags: [Submission]
      parameters:
        - in: query
          name: username
          schema:
            type: string
          required: true
          description: Username to filter by
        - in: query
          name: page
          schema:
            type: integer
          required: false
          description: Page number
        - in: query
          name: limit
          schema:
            type: integer
          required: false
          description: Items per page
      responses:
        '200':
          description: Submissions by user returned successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    text:
                      type: string
                    res:
                      type: string
        '400':
          description: Missing or invalid username
        '401':
          description: Unauthorized
        '404':
          description: User not found or no submissions
        '500':
          description: Server error

  /submissions/input:
    post:
      summary: Submit text for AI correction
      tags: [Submission]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                text:
                  type: string
              required: [id, text]
      responses:
        '200':
          description: Correction results returned
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  text:
                    type: string
                  res:
                    type: string
                  corrections:
                    type: array
                    items:
                      type: object
                      properties:
                        original:
                          type: string
                        corrected:
                          type: string
                        reason:
                          type: string
        '400':
          description: Missing fields
        '401':
          description: Unauthorized
        '500':
          description: Server error

  /submissions/comment:
    post:
      summary: Post a comment on a submission
      tags: [Comment]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                text:
                  type: string
              required: [id, text]
      responses:
        '201':
          description: Comment posted successfully
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Submission not found
        '500':
          description: Server error

  /submissions/comments:
    get:
      summary: Get comments for a submission
      tags: [Comment]
      parameters:
        - in: query
          name: id
          schema:
            type: string
          required: true
          description: Submission ID
      responses:
        '200':
          description: List of comments
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    user:
                      type: string
                    text:
                      type: string
        '400':
          description: Missing ID
        '404':
          description: Submission not found
        '500':
          description: Server error

  /submissions/human:
    post:
      summary: Submit human correction
      tags: [HumanCorrection]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                submissionId:
                  type: string
                corrections:
                  type: array
                  items:
                    type: object
                    properties:
                      original:
                        type: string
                      corrected:
                        type: string
                      reason:
                        type: string
              required: [submissionId, corrections]
      responses:
        '201':
          description: Human correction submitted
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Submission not found
        '500':
          description: Server error
    get:
      summary: Get human corrections for a submission
      tags: [HumanCorrection]
      parameters:
        - in: query
          name: submissionId
          schema:
            type: string
          required: true
          description: ID of the submission to retrieve human corrections for
      responses:
        '200':
          description: List of human corrections
          content:
            application/json:
              schema:
                type: object
                properties:
                  submissionId:
                    type: string
                  corrections:
                    type: array
                    items:
                      type: object
                      properties:
                        original:
                          type: string
                        corrected:
                          type: string
                        reason:
                          type: string
        '400':
          description: Missing or invalid submissionId
        '401':
          description: Unauthorized
        '404':
          description: Submission not found or no human corrections
        '500':
          description: Server error


  /submissions/delete:
    delete:
      summary: Delete a submission
      tags: [Submission]
      parameters:
        - in: query
          name: id
          schema:
            type: string
          required: true
          description: Submission ID
      responses:
        '200':
          description: Submission deleted successfully
        '400':
          description: Missing ID
        '401':
          description: Unauthorized
        '404':
          description: Submission not found
        '500':
          description: Server error

components:
  securitySchemes:
    SessionAuth:
      type: apiKey
      in: cookie
      name: sessionid

security:
  - SessionAuth: []
